# gitlab-ci

stages:
  - build
  - deploy

before_script:
  - curl -s toast.sh/install-v3 | bash

build:
  stage: build
  image: node:latest
  script:
    - ~/toaster/toast.sh prepare
    - ~/toaster/toast.sh build node
  artifacts:
    paths:
      - target/

deploy:
  stage: deploy
  image: python:latest
  script:
    - pip install awscli
    - ~/toaster/toast.sh deploy lambda resize

after_script:
  - ls -alh target
