# gitlab-ci

stages:
  - build
  - release
  - deploy

variables:
  FUNCTION: resize-dev
  S3_BUCKET: repo.nalbam.com
  S3_KEY: $CI_PROJECT_NAME/$CI_COMMIT_REF_NAME/lambda.zip

build:
  stage: build
  image: nalbam/builder:node
  script:
    - mkdir -p target
    - cd src && npm install && zip -r ../target/lambda.zip *
  artifacts:
    paths:
      - target/

release:
  stage: release
  image: nalbam/builder:python
  script:
    - aws s3 cp target/lambda.zip s3://$S3_BUCKET/$S3_KEY

deploy:
  stage: deploy
  image: nalbam/builder:python
  only:
    - master
  script:
    - aws lambda update-function-code --function-name $FUNCTION --s3-bucket $S3_BUCKET --s3-key $S3_KEY

after_script:
  - ls -alh
  - ls -alh target
