# gitlab-ci

stages:
  - build
  - release
  - deploy

before_script:
  - curl -s toast.sh/install-v3 | bash

build:
  stage: build
  image: nalbam/builder:node
  script:
    - ~/toaster/toast.sh build node
  artifacts:
    paths:
      - target/

release:
  stage: release
  image: nalbam/builder:python
  script:
    - ~/toaster/toast.sh release bucket
  artifacts:
    paths:
      - target/

deploy:
  stage: deploy
  image: nalbam/builder:python
  only:
    - master
  script:
    - ~/toaster/toast.sh deploy lambda resize-dev

after_script:
  - ls -alh target
